# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

def random_color
    "%06x" % (rand * 0xffffff)
end


Article.create!(
    title: "The 4500 Word Lorem Ipsum", 
    text: '<p>Lorem ipsum dolor sit amet quisque. Sed blandit et porta eget curabitur. Ut scelerisque arcu. Lacus odio risus eget orci netus nec nisl tristique. Ut tincidunt et. Euismod neque dui nec volutpat luctus. Non nullam tortor. Dolor vel massa. Viverra quis diam quam wisi dolor elit ac suspendisse lorem tristique interdum sit id amet. Ipsum id dolorum aliquam quis ut.</p>

<p>Lectus integer pede porta nullam mi. Massa vel neque tellus eleifend posuere. Ante ad amet etiam dolor ut lacus sollicitudin ante. Mattis pellentesque donec eu amet pharetra. Eget fringilla arcu.</p>

<p>Turpis at tempus amet vestibulum arcu. Turpis nonummy pharetra ipsum montes urna donec dui ut. In consectetuer neque lacinia quis eros. Sapien sed urna. Purus euismod suscipit. Enim massa donec habitant at elit diam interdum etiam at eu pretium. Ut semper maecenas fermentum sed faucibus dui dolor et. Faucibus elit vitae. Consectetuer at ornare. Est velit duis. Luctus morbi pede. Malesuada in nibh. Laoreet ipsum dictumst purus euismod ac. Dolores vivamus scelerisque non imperdiet justo nonummy nec imperdiet adipisci ultricies sed tortor vestibulum diam hendrerit nisl fermentum eu id non nulla iaculis platea. Lacus primis nulla. Fusce modi leo convallis leo odio vehicula adipiscing ipsum. Turpis in libero. Dapibus volutpat vestibulum. Lobortis venenatis nisl. Inceptos justo nec facilisis vestibulum interdum. Vestibulum vel nullam. Vestibulum auctor sed vitae sit wisi. Mus et elit in vel velit quis sem eget enim donec mus. Augue vel ut vestibulum suspendisse ullamcorper. Sed mollis ut.</p>

<p>Scelerisque sed ligula. Amet et curabitur sed neque a augue ultrices lobortis ut mauris amet. Vel semper pede pellentesque in in fames sit dolor diam consequat ornare. Hymenaeos scelerisque orci. Interdum aliquam erat. Proin maecenas non. At sed dolor. Donec laoreet nec. Amet nunc a. Urna tortor mollis arcu imperdiet turpis. Suspendisse arcu malesuada nibh facilisi elementum. Aliquam ut nullam neque vulputate diam a velit sed ac blandit augue. Id scelerisque elementum. Facilisi nulla diam eu sed eu wisi mauris tortor. Proin aenean erat. Libero fusce pellentesque. Felis nonummy et. Sodales feugiat suscipit quis sit eget. Et lobortis lectus ut iaculis sociosqu adipiscing blandit nonummy nunc imperdiet odio urna lacus duis sit nulla purus vivamus a et. Et turpis est.</p>

<p>Accumsan mi vel gravida dapibus vivamus ullamcorper ante morbi rutrum elementum pellentesque ut proin id. Quisque porttitor non. Hendrerit orci adipiscing. Etiam penatibus vitae nisl fermentum dapibus. Sit quis mus semper quisque pretium. Vitae lorem etiam suspendisse dictum cursus. Odio est dictumst aenean faucibus suscipit purus in curabitur. Sed massa dictum. Rhoncus sit culpa con hendrerit elit. Fringilla adipiscing dolor.</p>

<p>Euismod molestie urna. Dui eu eros. Duis id maecenas. Eget lacus est. Donec massa faucibus mauris tempor ultricies sociosqu tortor posuere nisl elit erat. Eu sit dapibus. Vehicula vivamus dis. Montes dui pellentesque. Sed lacus vel suspendisse malesuada nam. Donec nibh quam. Nulla vestibulum ut vestibulum aliquet sit id mollis in lorem aenean mattis. Lobortis adipisci faucibus turpis neque libero vestibulum et eget. Suscipit integer pede luctus magna lacinia. A ut adipiscing suspendisse nulla ante. Leo vitae purus. Dignissimos vitae imperdiet. At nunc facilisis proin earum minus. Dignissim pede amet. Scelerisque augue sodales eget fames justo cras rhoncus sollicitudin hic ullamcorper nullam. Phasellus aptent potenti. Nostra pharetra vel morbi dictum egestas non nisl qui. Luctus vel ante mollis massa augue. Ultrices pellentesque consectetuer suspendisse turpis scelerisque ut tristique sit. In curabitur in sit faucibus est scelerisque pellentesque quis. Integer interdum nulla do turpis netus et maecenas adipiscing amet congue quisque.</p>

<p>Quisque integer vivamus. Diam tristique leo quisque quam sit integer sit sapien. Porttitor in sed tellus nonummy sed convallis orci lectus. Magnis eius orci suscipit tincidunt elit. Duis dui porta. Mi in interdum posuere auctor lectus. Cras vivamus augue. Pulvinar velit rhoncus tempor sapien nascetur lorem feugiat dui etiam quis libero. Nec lacus quis vitae molestiae netus. Enim posuere lobortis lorem metus metus. Libero iaculis tincidunt dapibus nulla malesuada ligula elit wisi. In ante phasellus. Maecenas justo con. Ligula risus cras mauris consequat mauris. Id rhoncus tellus. Mi in vel. In quis cursus morbi vitae lacus tristique pede wisi ut lorem at elementum platea risus. Proin quis ullamcorper molestie adipiscing a. Amet sed sem magna diam ante quam massa elit nostra sit id. Consequat non dictum suspendisse a rutrum. Vel posuere bibendum. Lorem nullam bibendum est facilisis purus erat scelerisque suspendisse. Tempus a neque. Tristique consequat hendrerit. Iaculis eget amet pretium eros eu. Quis sed donec. Vel eros dolor vel integer aliquam. Rutrum ultricies nulla metus bibendum sapien neque purus maecenas ac quis eget ipsum lobortis elementum rutrum dolor scelerisque. Arcu suspendisse elit. Commodo sed dapibus. Ut sit vestibulum eu massa ut. Justo elit in volutpat mauris donec fermentum volutpat a in maecenas non aliquet at elementum. Euismod nunc nunc ipsum tellus purus. Lorem augue tristique. Augue ut accusamus. Ante cras quisque. Ligula quis condimentum. Voluptas aliquet orci. Amet eu vestibulum massa nascetur potenti. Ut metus risus eros natoque integer.</p>

<p>Ullamcorper potenti fugiat. Est feugiat in conubia duis justo. Neque augue euismod. Sed arcu aenean ut nisl taciti. Ornare libero vitae. Sed risus urna nec vel vitae diam elit diam vitae eget nisl ut nec tristique nunc risus conubia. Vestibulum luctus rhoncus et a assumenda. Quisque id diam wisi in erat. Feugiat eu vel. Neque senectus id. Aliquam at tempor. Id orci risus. Ornare felis imperdiet. Lectus et ipsum. Purus vivamus donec imperdiet nulla auctor. Mauris justo eu ac ultricies ut. Convallis libero integer non dapibus interdum. Quis nibh a. Ac class lorem. A ut porttitor. Massa consequat proin aliquam non sociis mattis quis imperdiet libero non at. Et felis eget erat lectus a hendrerit quam ullamco quam ac ante. Laoreet ut ut eget aenean maecenas accumsan felis ut. Sed dui arcu. Semper ut tristique enim fringilla risus. Donec felis quis. Enim eget facilisi commodo tincidunt sociosqu. Per adipiscing viverra. Interdum dui porttitor vehicula diam placerat tempus quam fusce curabitur ut ante erat libero donec tempus viverra erat mattis rutrum pellentesque justo nec vitae urna amet orci. Non in at.</p>

<p>Vivamus habitasse aliquam. Magna sit morbi. Lorem ultrices nunc. Omnis purus metus lacus a lorem. Eget ipsa enim nullam morbi pede. Sit quia convallis arcu tristique primis. Vitae cras arcu ut nec aliquam nunc nec hendrerit. Non pede nulla. Mollis sapien nec. Libero sed nunc ultrices odio in. Nec aliquam fringilla. Nulla semper turpis. Eget tortor luctus. Ante lectus bibendum. Amet mattis mollis donec blandit urna quam eget lorem. A rhoncus pellentesque vulputate justo eu. Est felis nibh risus lobortis metus metus tortor dicta. Erat a eget vel quisque rhoncus vulputate magna ante. Praesent erat vestibulum sit urna phasellus felis consectetuer mauris. Volutpat et libero ut in consectetuer. Sapien luctus pellentesque mi semper ornare at at at. Vitae egestas erat suscipit rutrum erat lobortis lorem sed. Consequat fusce sit sed odio vivamus. Penatibus phasellus leo id at sed consectetuer integer vivamus. Leo et a in nascetur vestibulum nibh erat eros.</p>

<p>Aliquet netus porta. Sed donec scelerisque odio porta arcu orci quis sed est ornare ante lacus eleifend tellus. Neque pede ac. Rerum mi senectus. Massa erat vestibulum nulla augue quam.</p>

<p>Enim id in. Ipsum arcu pellentesque. Scelerisque tristique in. Non mollis mi tellus nunc ipsum elit accumsan perspiciatis non velit mauris adipiscing vulputate suspendisse sagittis morbi tincidunt. Ut orci eum.</p>

<p>Bibendum at nam. Eu orci neque conubia quisque suspendisse. Ipsum purus et tempus in turpis quam senectus felis. Gravida ultricies massa. Euismod adipiscing vel sollicitudin in in tellus dapibus leo.</p>

<p>Arcu in velit. Augue est sit. Dictum sapien varius. Vehicula integer venenatis modi tempus mauris donec nulla interdum quis mauris adipiscing urna odio ipsum. Malesuada libero mauris. Arcu cursus enim. Sed quis convallis proin a suscipit. Eros vestibulum tellus. Urna luctus penatibus eu molestie et posuere vel quam sed ante gravida. Primis urna diam donec sed arcu elit amet nulla dolor senectus lorem habitasse ut nisl. Massa sagittis non in placerat vitae est egestas nec velit est nunc. Ornare nam nulla. Donec rhoncus suspendisse amet sagittis sollicitudin ad sed eu. Ipsum illum fusce. Suscipit mauris ut. Molestie nec urna vitae in risus. Dolor orci nulla nec pede ipsum. Justo placerat mi. Augue purus integer. Per cursus turpis nec vitae molestie.</p>

<p>Maecenas sed at. Bibendum auctor mi nulla venenatis neque. Nam sodales ut. Massa nulla elit natoque nunc aliquam. Tristique nam magna massa ut vivamus. Dignissim varius dolor pellentesque feugiat vitae viverra vulputate at tincidunt neque sem. Eu lectus aenean. Porta augue praesent lectus dapibus dignissim. Eros ut donec. Amet massa praesent. Pellentesque enim facilisis. Aptent lectus fusce ante enim justo tristique natoque proin. Arcu eget pellentesque. Mattis maecenas tempus fusce con purus. Metus et orci amet pellentesque adipiscing. Eget optio neque ac neque elit augue donec vel. Mi lacinia vel. Natoque quisque blandit. Adipiscing eu sapien. A nullam laoreet felis eget purus per vivamus et. Et viverra velit. Euismod nonummy nibh. Enim et neque. Maecenas facilisis vulputate ipsum tristique culpa quidem vitae et. Eius gravida bibendum elit erat eu. Posuere tempus praesent. Magna cras leo dignissim libero sit sit tortor vulputate. Dolor arcu bibendum rutrum enim ornare. Rutrum turpis dolor. Sollicitudin etiam nonummy massa at eu nulla enim praesent libero in sapien sed con ligula velit vehicula et. Et proin optio velit odio nunc. Ultrices sem ac. Orci neque cras. Vivamus lobortis sit. Non nec enim. Arcu est velit ut ante libero quis duis nullam. Leo turpis vivamus. Eget ultricies ante. Sed sit imperdiet in adipiscing odio urna suspendisse mauris. Consequat lobortis sodales diam mi vulputate sunt magnis platea quis nunc arcu. Imperdiet wisi integer adipiscing quam vehicula imperdiet curabitur temporibus donec commodo sem gravida amet mattis. Tortor sed commodo turpis ipsum consectetuer urna vitae mollis. At eleifend donec ullamcorper neque urna vivamus vitae feugiat egestas hendrerit iaculis. A varius arcu. Nunc id mi interdum massa nunc curabitur at sagittis.</p>

<p>Donec libero pede diam in aliquam mauris posuere libero. Malesuada nibh scelerisque non amet dui nulla sollicitudin odio porta ad fugit curabitur dictumst ac. Nunc curabitur lorem elit eget posuere. Wisi pellentesque quisque velit elementum est. Lectus malesuada pellentesque. Pulvinar integer sit vivamus donec vel nec vel in curabitur pretium ipsum. Hendrerit turpis dui. Sed interdum pellentesque dictum nonummy tristique. Montes eget integer. Nisl integer turpis. In malesuada morbi id montes metus vestibulum quis sit. Amet amet wisi turpis turpis magna. Wisi varius ultrices. Auctor fusce sed tempus vitae rutrum iaculis pede maecenas. In dolor scelerisque. Sapien blandit placerat nulla est ac. Eget nulla eros ac ut etiam. Et leo parturient tincidunt donec arcu. Id mattis hac nullam aenean ac. Et mattis rhoncus. Rutrum sagittis iaculis elit tortor sem elementum diam nunc condimentum nec quam. Urna pellentesque rutrum. Wisi gravida augue. Dolor placerat tellus. Morbi ultrices hymenaeos elementum varius eros.</p>

<p>Sem dictumst est. Suspendisse fermentum vestibulum diam eu etiam faucibus iaculis amet pede feugiat arcu nisl tortor sagittis pulvinar nibh elit. Pellentesque congue sollicitudin adipiscing arcu aptent. Vitae gravida elementum. Et magni in. Urna ultricies sed. Eget sapien viverra. Convallis vestibulum justo maecenas augue tortor. Nulla augue proin est molestie arcu. Etiam pellentesque et vel viverra lorem. Adipiscing sapien vestibulum consectetuer at tellus. A orci morbi molestias eu fringilla. Risus vitae placerat. Nulla sed semper. Mauris elit mollis. Lectus nullam sapien hac elit lacus. Lorem sapien nec ut consequat dui. Dolor posuere enim labore posuere velit diam provident interdum quam ac nunc. Habitasse nibh rhoncus per mattis tempus sed blandit diam sed nulla ac ut non ultrices donec amet quam. Egestas convallis proin metus dictum pede mauris ipsum risus. In suspendisse vel. Sed in ipsum eu amet sapien. Vulputate dui vivamus etiam mattis ut. Erat ullamcorper dis. Magnis ante elit.</p>

<p>Donec risus urna mauris mauris nibh. Donec in sit. Nec wisi rhoncus. Ridiculus augue dolor nonummy auctor dui. Ut montes at dapibus tincidunt wisi felis quam in nulla ultrices felis. Eget porttitor hymenaeos venenatis donec scelerisque. Ac etiam arcu. Integer tellus wisi. Hac vivamus ornare sed nulla enim ut faucibus aliquam tempus mauris vitae. Sed ut aliquam sed tempor mus.</p>

<p>Egestas nisl mauris. A aliquet nunc. Tempus tincidunt et aliquam aptent orci. Nullam lacinia tempor urna viverra mi wisi ac vestibulum vel consequat diam. Id suspendisse lectus nulla aliquam auctor dui pellentesque sem. Donec metus vestibulum. Vehicula lectus duis. Sed ligula sapien nullam ultrices vivamus. Vitae tempus vestibulum wisi in pretium lectus varius augue in in magna. Aliquam bibendum nec quis itaque fugiat. Diam diam augue. Pulvinar wisi in. Quisque augue feugiat. Sed adipiscing enim eget vulputate torquent pulvinar primis quis. Libero vestibulum pede quis magna tellus eu viverra eget.</p>

<p>Magna non gravida consequat sollicitudin leo sed diam et etiam vestibulum laoreet nam velit nunc libero eget a semper feugiat dui. Suspendisse in pulvinar. Ac dui dui. Metus neque nec dicta faucibus placerat. Morbi ut ligula parturient molestie sagittis. Libero rutrum vehicula. Vitae potenti turpis. In vitae dapibus. Malesuada mollis semper nec amet mauris. Pede gravida at. Ultricies nibh a sed lacus vel. Senectus nulla nullam ridiculus urna nibh. Viverra nec commodo. Justo pede fusce. Aliquam iaculis vulputate malesuada commodo in sapien nibh metus. Morbi justo lectus. Ut aenean vitae. Aliquet inceptos eu. Faucibus sed amet ante neque parturient pellentesque nam eros dolor sit nisl hac condimentum sollicitudin. Pellentesque interdum orci fringilla semper magna elit ultrices ullamcorper. Ante convallis nulla. Cras sed etiam augue felis ut. Et lacus vitae amet pulvinar ullamcorper vivamus congue scelerisque. Arcu ultricies luctus maxime ut orci eu morbi orci pede leo lacus massa convallis optio. Nunc pellentesque nunc molestie magna metus. Vitae non magna orci curabitur nullam incidunt wisi neque. Duis integer adipiscing non ornare dolor. Ut venenatis nec eu et hac. Interdum tortor erat. Venenatis porta tempor nulla at malesuada. Eu nec varius. Mauris vitae ornare. Phasellus praesent aliquip aliquam nulla non venenatis maecenas condimentum. Ridiculus arcu curae nec lorem egestas. Suspendisse ultrices eu ligula porttitor primis. Eget orci class rutrum molestie lectus. Egestas nulla lorem orci placerat orci porttitor accumsan amet. Id erat nec ligula nam metus. Aliquam justo odio sit dignissim molestie. Convallis amet vel venenatis nec at. Tristique curae perferendis. Convallis sit mi. Sit urna tortor. Integer mollis integer eget velit rerum turpis lectus eget. Sed sed blandit nunc mauris risus.</p>

<p>Suspendisse tristique sem accumsan habitasse aliquam id hendrerit felis mauris enim sit. Diam vel vitae. Sed euismod lacus pulvinar nulla in non eget vehicula amet tincidunt mattis. Vel ante sed massa ut donec. Egestas fermentum rutrum. Donec amet commodo. Varius vel scelerisque. Eget vestibulum molestie. Esse vitae aut sagittis sodales erat. Integer imperdiet elit wisi interdum penatibus porta massa platea. Eget ultrices orci. In metus cursus fusce varius posuere mauris urna pede lectus quis nunc urna diam iaculis. Egestas nonummy pede morbi vel porta leo sit adipiscing vestibulum mauris vivamus quam nec commodo risus interdum cras justo sit pulvinar. Sunt odio justo porttitor vestibulum aliquam mattis ut arcu quis dolor etiam. In ligula ultrices maecenas at vitae elit urna suspendisse tempus et dolor. Maecenas eu eu sed sed sociosqu curabitur id mattis adipiscing nam netus. In eros enim. Morbi est eleifend. Ullamcorper sagittis nonummy. Blandit vitae convallis. Pellentesque velit potenti. Ipsum ut fringilla. Per integer est et turpis augue. Felis quam lorem. Turpis erat elementum ullamcorper laoreet magna luctus consectetuer viverra ac felis lacinia molestie erat magna. Vitae cras duis. Ac dictum in. Libero maecenas amet magna placerat dolor pretium pharetra penatibus a integer hendrerit. Orci nulla non. Rutrum a elementum praesent orci a. Lacus nam nullam. Ipsum parturient lorem eos porro tortor elit nonummy elit sodales nunc consequatur odio suspendisse ipsum. Vel interdum placerat ut elit ut. Curabitur donec dis quisque vitae id. Et pede et. Nec dis tortor. At justo semper penatibus sollicitudin ac montes id porta. Pretium a ante ut quis ac rutrum urna dapibus. Amet magna eget. Dui cras leo. Etiam est elit aliquam egestas integer adipiscing rhoncus porttitor nonummy nunc eget ac velit torquent. Interdum arcu quis. Vestibulum illo lorem metus mauris et. Dignissim ad posuere ac eu donec. Non ut elementum. Consectetuer mollis at. Amet donec lectus. At pellentesque vitae. Velit sed luctus consequat tellus sed. Ante platea lorem. Pharetra eu in. Augue metus et. Ornare facilisi quis. Pellentesque hendrerit sed purus eu in. Nunc tincidunt libero. Amet pellentesque vitae dolor est elit. Phasellus urna in. Eos pellentesque et malesuada et odio. Enim enim rhoncus quisquam ligula ut ut vivamus ipsa. Praesent vel leo.</p>

<p>Nascetur nullam at natoque adipiscing ultricies. Mi nibh a. Et maecenas risus mi eleifend enim consequat ultricies odio. Primis proin porta luctus pretium eu tellus elit habitasse lectus elementum nullam commodo felis tristique aenean interdum pulvinar. Quisque tincidunt massa. Amet sed egestas. In nec nam. Egestas ridiculus accusamus. Consectetuer sagittis orci mauris pretium sollicitudin orci nam praesent vulputate integer laoreet. Dignissim scelerisque a interdum sit rhoncus est justo aliquam mauris tellus duis. Morbi dui arcu mauris felis commodo fusce donec nisl ut mi sociis sit neque vestibulum cursus orci in. Blandit sodales suspendisse. Ipsum aliquam lacus morbi dui est vestibulum mauris sapien. Amet suspendisse nulla. Cras praesent tellus. Integer ut ultricies cursus nec pharetra. Nec turpis sed. Amet suspendisse eu. Asperiores porttitor diam. Elementum sodales proin. Sed integer lobortis metus sed vitae. Mi consequat tellus. Viverra varius feugiat. Elementum wisi commodo. Neque suscipit lacus lacus erat placerat eget commodi massa.</p>

<p>Sit et ut. Pellentesque leo neque. Aliquam dignissim vel enim lacus elementum. Purus non metus pede per sed. Feugiat dis vel. Suscipit arcu nunc feugiat ligula faucibus non morbi nam. Aliquam purus sem. Integer a ut donec in est felis ut urna integer quis elit eros laoreet pellentesque dictumst ac felis. Sit purus accumsan class aliquam libero. Massa faucibus sodales sapien aliquam amet. Id at mauris arcu maecenas praesent enim sit lacus. Hac semper mauris. Integer mus et iaculis sed ante. Mi et in. Vivamus velit ante tempor dictum et.</p>

<p>Praesent consequat vitae. Augue erat ac. Justo massa vel ligula et vitae amet turpis curabitur sem sociosqu malesuada. Metus urna mollit non accumsan lectus. Fringilla convallis et sollicitudin integer mauris. Vestibulum nibh ut hendrerit venenatis ut elit sem consectetuer condimentum dui ullamcorper consectetuer mi id. Quam sem ac. Faucibus a sodales distinctio tempus nibh. Bibendum mauris proin odio auctor dolor aut justo volutpat. Elit vel leo. Feugiat wisi orci laoreet consequat sit. Lacus risus sem. Feugiat rhoncus fusce. At ligula lacinia parturient sed fermentum. Sollicitudin at est elit vitae condimentum.</p>

<p>Vitae nullam ultrices suspendisse urna non. Adipiscing eros aliquam at ante scelerisque. A leo hendrerit orci venenatis in. Etiam nibh viverra ac parturient justo. Cursus platea vel. Ipsum pretium aptent feugiat urna sit sed adipiscing quam. Tincidunt sed donec. Ultricies lectus amet. Sit at mauris suscipit volutpat condimentum id elementum adipiscing quam et vivamus. Turpis ea et sed pellentesque ligula. Duis luctus vitae tempus velit posuere. Incididunt etiam nunc. Ultricies eu metus. Lacus ac quis accumsan sit ac. Sed integer con parturient ad habitasse mauris illo consectetuer varius vestibulum nulla. Phasellus ac nibh. Lectus per vel in fusce morbi sit in urna. Corrupti ut volutpat ornare at lobortis. Conubia dolor platea. Porta quos erat. Id platea augue pellentesque ullamcorper convallis. Tellus sit massa dui id lorem rutrum molestie congue. Feugiat bibendum elit. Tortor ligula velit torquent dolor eu. Donec sollicitudin sed vel vestibulum dictum arcu at feugiat nunc sed interdum.</p>

<p>Fringilla eu sodales autem faucibus sagittis. At purus feugiat. Ut mus a rutrum tempor cubilia diam euismod tellus. Per donec ante nisl ac rhoncus. In a lorem dolor mauris vestibulum.</p>

<p>Imperdiet ipsum commodo tincidunt nam nunc bibendum nibh velit. Nunc urna elementum phasellus ut tortor. Dui in placerat. Nulla fringilla malesuada suscipit aptent sed tristique pulvinar id. Aliquam diam tellus.</p>

<p>Ultricies arcu eget ultrices dolores lorem. Etiam tincidunt lorem. Consequat ut ullamcorper nisl at lorem faucibus dis tincidunt aliquam ac sed erat ac nulla. Odio tristique auctor sociis nemo quis. Odio sed quisque. Velit netus sed nulla ac ut nulla aliquam quam et wisi fringilla quam justo dapibus sit neque elit eros convallis elementum pulvinar tempus egestas. Ultrices sodales non. Venenatis at aliquet odio vitae facilisi. Erat class et. Molestie justo non. Pulvinar eget elementum. Libero arcu habitasse enim fusce mattis sed vitae sit. Nulla sed convallis sagittis tellus arcu. Vitae fermentum condimentum. Vivamus ultrices commodo. Et elit ut. Massa nulla wisi vitae dolor elementum integer nulla lacinia vel sed id. Nisl tempor in etiam scelerisque in. Accumsan auctor aliquam tellus et diam. Quam proin ut eros cursus est. Enim dui imperdiet quis netus nec. Fusce maecenas elit. Placerat nulla in. Pharetra dolor suspendisse laoreet lacus integer ac in felis risus in laoreet. Elit eu dolor. Fermentum semper eu volutpat vestibulum faucibus. Pellentesque nullam tempus odio urna congue mollis neque dolor id ipsum risus. Duis lorem netus. Ante pellentesque vestibulum metus risus libero. Aenean magna diam. Porttitor arcu scelerisque netus ut tristique. Velit quis suspendisse arcu scelerisque praesent quam ac eros hendrerit in nec sed facilisis id felis euismod felis libero ultricies at. Nibh mollis quis. Metus scelerisque leo. Urna elit nonummy. Sapien dis interdum tincidunt elit pede. Nulla mauris nonummy. Porttitor in tincidunt. Nibh et quisque. Turpis sagittis nullam.</p>

<p>Ut fermentum vestibulum venenatis iaculis felis. Senectus est quam. Vestibulum neque eu. Maecenas amet sed. Cras mi congue aliquam porta aliquam aliquam facilisis nisl et torquent metus. Ac mauris malesuada eget eget enim. Massa eget temporibus. Nam convallis mattis leo pellentesque porta volutpat cras elit in cras suscipit morbi nulla molestie congue commodo lorem. Ad placerat placerat. Est duis maecenas pretium magnis et. Orci non sit. Sed dolorem viverra mauris faucibus vitae suscipit tellus mattis. Luctus diam lobortis. Rutrum a eros nibh enim pellentesque. Congue accumsan nibh odio urna integer.</p>

<p>Maecenas ipsum nisl mauris ac habitasse. Neque duis vestibulum. Urna libero enim ut volutpat donec. Sociis nibh sed quisque urna quam orci aliquam elit. Vitae ultrices purus nec egestas et.</p>

<p>Donec lorem libero. Quam tortor elit mauris ut posuere mi dictum sem ante nam minus ut mauris condimentum duis sit vitae. Sodales vestibulum vitae. Accumsan nunc nec. A litora nunc. Vel id purus. Consectetuer nec sit commodo pharetra eros penatibus diam id. Massa tincidunt vehicula lectus ante sit ornare vel quisque. Felis vestibulum vestibulum. Lacinia condimentum porttitor. Amet enim ad pede est lacus bibendum vestibulum justo fringilla ad tortor. Ipsum arcu suspendisse ut natoque pede. Ornare vivamus nullam. Mollis risus purus porta ac vel. Velit amet felis auctor ut urna.</p>

<p>Posuere fusce sed lectus vitae eu id velit curabitur fermentum duis pharetra velit ante risus vitae integer velit. A ac sit ante laoreet ridiculus. Cras quam hendrerit. Libero lacus vulputate duis blandit maecenas. Aliquam id amet. Nam amet integer. Magnis urna integer. Nulla elit vitae tincidunt omnis turpis. At magna arcu dapibus mauris nonummy. Condimentum magna proin. Sed est vitae. Ultricies risus a. Suscipit congue dolor auctor posuere sit. Morbi nam tellus mattis pellentesque sapien suscipit id odio ut eget elementum sed mauris sit libero commodo quam. Curabitur sodales in.</p>

<p>Sodales congue mauris. Integer eros odio tellus nec vehicula. Suspendisse vitae id id vitae iaculis. Dis ut nullam. Vitae dolor tempus mollit integer vestibulum. Lacinia venenatis pellentesque. Turpis ut libero elit blandit sed nulla urna donec. Odio eros dui nibh est in. Suspendisse massa egestas leo sed fusce. Pharetra ipsum orci sollicitudin cras penatibus. Viverra lectus ante ut sed pulvinar. Ridiculus ac pretium proin et neque. Egestas luctus posuere. Porta ac nulla. Amet purus amet integer ultrices cursus eget tempor sit mus donec sit nunc at vestibulum pede per vitae sapien placerat blandit. Alias dolor sit. Leo massa ut. Enim lobortis mattis. Accumsan sollicitudin ut leo commodi mollis rhoncus id fringilla. A inceptos sapien dapibus non phasellus sollicitudin mi nulla. Mi fusce nunc. Montes libero pellentesque. Mauris praesent odio eu wisi lacus amet condimentum sollicitudin. Viverra laudantium cras sed dis et semper morbi nostra ac nullam irure bibendum eros condimentum. Id ut libero aenean ligula taciti bibendum et sociis felis turpis dui. Perspiciatis suscipit egestas. Dignissim semper proin. Ligula massa fusce. Eros curabitur vehicula tortor lacinia urna. At scelerisque magna.</p>

<p>Ipsum aliquet ut. Et feugiat consectetuer aliquid ridiculus augue. Atque mauris ut. Amet faucibus libero porta ut urna. Integer natoque nullam. Risus nec justo amet rutrum corrupti semper elit ullamco. Nisl orci aliquam sunt maecenas non. Rutrum con ante nec parturient eget semper consectetuer elementum blandit velit sed tortor habitasse ipsum non in nulla vestibulum nonummy velit. Semper est nascetur. Amet risus pellentesque. A mauris nibh magna maecenas pulvinar tincidunt iste sed amet ultrices tincidunt viverra sapien semper. Sed ac non. Venenatis porttitor urna arcu massa placerat lacinia eget varius. Tempor sit integer. Maecenas eleifend augue. Metus volutpat nullam. Dapibus ornare non. Dolor habitasse dolor. Porttitor enim mauris. Nostra quis nulla aliquam eget vestibulum. Quis sollicitudin nullam. Ullamcorper vestibulum purus. Magna inceptos mauris ac sollicitudin mauris mi commodo ultricies natoque tristique ut at non sit morbi integer potenti morbi velit wisi primis molestie libero tellus erat imperdiet consequat donec praesent tellus in turpis. Nam dolor lacinia. Ut tellus sit in donec elit varius urna est felis ultricies faucibus. Erat aut nulla. Erat ac metus. Tellus enim dapibus. Donec varius nunc. Odio bibendum morbi. Duis maecenas risus suscipit rutrum sit. Vitae suspendisse fusce. Convallis porttitor ante neque ut mi. Deserunt wisi tincidunt. Metus et sed suscipit euismod justo dolor enim a.</p>

<p>Vel metus tempus. Dolore facilisis nonummy. Phasellus curabitur hendrerit cursus lectus amet congue velit nunc. Sit nam pharetra. Urna arcu eros etiam vel eu magna ornare id mattis tortor vestibulum a velit et. Sed non ut. Felis facilisis nulla morbi vivamus posuere ac ut a. Augue magnis vehicula nam amet sem. Id sit sem. Scelerisque gravida ornare. Mattis varius elit lobortis mauris wisi. Vitae mauris molestie. Laoreet ligula id curabitur aliquet aliquet nunc pede orci lectus mi turpis lectus id voluptas egestas massa magna. Urna sem ac. Quam rhoncus nunc.</p>

<p>Purus congue egestas. Nulla pede elementum. Sed ultrices condimentum. Amet dolore tincidunt vivamus pede mi. Imperdiet mauris est. Ut sed porttitor nam molestie nullam. Orci ut dolor suspendisse nunc in fames vestibulum eget inceptos ac pede. Lorem nam eget ullamcorper imperdiet sed sed convallis at. Turpis eleifend elit. Fusce metus sed aenean facilisis donec elit at sed bibendum vehicula malesuada.</p>

<p>Elementum primis nam. Lorem quam fusce porttitor lobortis semper porttitor in integer ut litora sed morbi diam natoque mauris aliquam quis. Morbi quis enim. Nonummy ullamcorper risus. Convallis lorem cursus. Euismod molestie consectetuer nonummy tristique pede. Donec eros dui rutrum velit bibendum. Varius nulla sapien dolor mollis nulla risus venenatis officia. Pede pulvinar iaculis. Nulla sed cursus enim vivamus libero.</p>

<p>Nec a dui. Orci et imperdiet ut hendrerit arcu mauris dui suspendisse. Risus in libero. Dolor enim ut. Eget et amet phasellus vestibulum justo. Lectus volutpat convallis amet maecenas lectus. Sem scelerisque ultricies metus eleifend et sed mi consequat. Suspendisse ac mi eros sodales ipsum. Nibh ridiculus ipsum. Sed interdum nec eu dignissim tellus diam malesuada enim sit et nec.</p>

<p>Quis cursus id pellentesque adipiscing aenean. Ut semper interdum habitant non placerat. Ante urna egestas. Mi mollis orci dictum vitae dui. Ipsum maecenas vestibulum morbi proin massa neque mi sed dui sapien maecenas egestas sed vitae. Vivamus dui dictum. Sint nonummy pretium velit facilisis sed. Magnis et at senectus suspendisse laoreet. A sed eu libero odio eros. Dapibus vel quam.</p>
', 
    average_color: "##{random_color}", 
    font_color: "##{random_color}",
    user_id: 1
    )


